# Generated by Django 6.0.1 on 2026-05-16 03:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='away_team_score',
            field=models.IntegerField(default=0, verbose_name='アウェイチーム得点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='home_team_score',
            field=models.IntegerField(default=0, verbose_name='ホームチーム得点'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DiaryPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diary_photos/', verbose_name='写真')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='games.diary', verbose_name='観戦記録')),
            ],
        ),
    ]
