# Generated by Django 6.0.1 on 2026-05-23 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_diarypicture_created_at_diarypicture_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarypicture',
            old_name='image',
            new_name='picture_url',
        ),
    ]
