# Generated by Django 6.0.1 on 2026-07-01 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arena_category', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'アリーナカテゴリ',
                'verbose_name_plural': 'アリーナカテゴリ',
                'db_table': 'arena_category',
            },
        ),
        migrations.CreateModel(
            name='Spot_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_category', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '周辺施設カテゴリ',
                'verbose_name_plural': '周辺施設カテゴリ',
                'db_table': 'spot_category',
            },
        ),
        migrations.CreateModel(
            name='ArenaFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arena_name', models.IntegerField(choices=[(1, '北海きたえーる'), (2, 'ゼビオアリーナ仙台'), (3, 'CNAアリーナ★あきた'), (4, 'アダストリアみとアリーナ'), (5, 'ブレックスアリーナ宇都宮'), (6, 'OPEN HOUSE ARENA OTA'), (7, '越谷市立総合体育館'), (8, 'LaLa arena TOKYO-BAY'), (9, '千葉ポートアリーナ'), (10, 'TOYOTA ARENA TOKYO'), (11, '青山学院記念館'), (12, '東急ドレッセとどろきアリーナ'), (13, '横浜国際プール'), (14, '富山市総合体育館'), (15, '豊橋市総合体育館'), (16, 'ウィングアリーナ刈谷'), (17, '名古屋市枇杷島スポーツセンター'), (18, 'IGアリーナ'), (19, '滋賀ダイハツアリーナ'), (20, 'にっしんでんきアリーナ京都'), (21, 'おおきにアリーナ舞洲'), (22, '松江市総合体育館'), (23, '広島サンプラザホール'), (24, 'SAGAアリーナ'), (25, 'HAPPINESS ARENA'), (26, '沖縄サントリーアリーナ')], default=1, verbose_name='アリーナ名')),
                ('kids_space', models.ImageField(choices=[(1, '有'), (2, '無')], default=2, upload_to='', verbose_name='キッズスペース')),
                ('diaper_table', models.IntegerField(choices=[(1, '有'), (2, '無')], default=2, verbose_name='おむつ交換台')),
                ('nursing_room', models.IntegerField(choices=[(1, '有'), (2, '無')], default=2, verbose_name='授乳室')),
                ('review', models.CharField(max_length=1000, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spots.arena_category', verbose_name='アリーナカテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': 'アリーナ情報',
                'verbose_name_plural': 'アリーナ情報',
                'db_table': 'arena_facilities',
            },
        ),
        migrations.CreateModel(
            name='ArenaNearbySpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arena_name', models.IntegerField(choices=[(1, '北海きたえーる'), (2, 'ゼビオアリーナ仙台'), (3, 'CNAアリーナ★あきた'), (4, 'アダストリアみとアリーナ'), (5, 'ブレックスアリーナ宇都宮'), (6, 'OPEN HOUSE ARENA OTA'), (7, '越谷市立総合体育館'), (8, 'LaLa arena TOKYO-BAY'), (9, '千葉ポートアリーナ'), (10, 'TOYOTA ARENA TOKYO'), (11, '青山学院記念館'), (12, '東急ドレッセとどろきアリーナ'), (13, '横浜国際プール'), (14, '富山市総合体育館'), (15, '豊橋市総合体育館'), (16, 'ウィングアリーナ刈谷'), (17, '名古屋市枇杷島スポーツセンター'), (18, 'IGアリーナ'), (19, '滋賀ダイハツアリーナ'), (20, 'にっしんでんきアリーナ京都'), (21, 'おおきにアリーナ舞洲'), (22, '松江市総合体育館'), (23, '広島サンプラザホール'), (24, 'SAGAアリーナ'), (25, 'HAPPINESS ARENA'), (26, '沖縄サントリーアリーナ')], default=1, verbose_name='アリーナ名')),
                ('spot_name', models.CharField(max_length=30, verbose_name='スポット名')),
                ('review', models.CharField(max_length=1000, verbose_name='見どころ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spots.spot_category', verbose_name='周辺カテゴリ')),
            ],
            options={
                'verbose_name': 'アリーナ周辺施設情報',
                'verbose_name_plural': 'アリーナ周辺施設情報',
                'db_table': 'arena_nearby_spots',
            },
        ),
    ]
