# Generated by Django 6.0.1 on 2026-07-04 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenafacility',
            name='kids_space',
            field=models.IntegerField(choices=[(1, '有'), (2, '無')], default=2, verbose_name='キッズスペース'),
        ),
        migrations.AlterField(
            model_name='arenafacility',
            name='review',
            field=models.TextField(verbose_name='口コミ'),
        ),
        migrations.CreateModel(
            name='ArenaFacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='arena_reviews/')),
                ('arena_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spots.arenafacility')),
            ],
        ),
    ]
