# Generated by Django 6.0.1 on 2026-07-04 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_alter_arenafacility_kids_space_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenafacilityimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arenafacilityimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='arenafacilityimage',
            name='image',
            field=models.ImageField(upload_to='arena_facility_images/'),
        ),
    ]
