# Generated by Django 6.0.1 on 2026-07-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_arenafacilityimage_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaNearbyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='arena_nearby_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('arena_nearby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spots.arenanearbyspot')),
            ],
        ),
    ]
