# Generated by Django 6.0.1 on 2026-09-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_arenanearbyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenafacility',
            name='diaper_table',
            field=models.IntegerField(blank=True, choices=[(1, '有'), (2, '無')], null=True, verbose_name='おむつ交換台'),
        ),
        migrations.AlterField(
            model_name='arenafacility',
            name='kids_space',
            field=models.IntegerField(blank=True, choices=[(1, '有'), (2, '無')], null=True, verbose_name='キッズスペース'),
        ),
        migrations.AlterField(
            model_name='arenafacility',
            name='nursing_room',
            field=models.IntegerField(blank=True, choices=[(1, '有'), (2, '無')], null=True, verbose_name='授乳室'),
        ),
    ]
