# Generated by Django 6.0.1 on 2026-05-15 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arena_name', models.IntegerField(choices=[(1, '北海きたえーる'), (2, 'ゼビオアリーナ仙台'), (3, 'CNAアリーナ★あきた'), (4, 'アダストリアみとアリーナ'), (5, 'ブレックスアリーナ宇都宮'), (6, 'OPEN HOUSE ARENA OTA'), (7, '越谷市立総合体育館'), (8, 'LaLa arena TOKYO-BAY'), (9, '千葉ポートアリーナ'), (10, 'TOYOTA ARENA TOKYO'), (11, '青山学院記念館'), (12, '東急ドレッセとどろきアリーナ'), (13, '横浜国際プール'), (14, '富山市総合体育館'), (15, '豊橋市総合体育館'), (16, 'ウィングアリーナ刈谷'), (17, '名古屋市枇杷島スポーツセンター'), (18, 'IGアリーナ'), (19, '滋賀ダイハツアリーナ'), (20, 'にっしんでんきアリーナ京都'), (21, 'おおきにアリーナ舞洲'), (22, '松江市総合体育館'), (23, '広島サンプラザホール'), (24, 'SAGAアリーナ'), (25, 'HAPPINESS ARENA'), (26, '沖縄サントリーアリーナ')], default=1, verbose_name='会場')),
                ('home_team_name', models.IntegerField(choices=[(1, 'レバンガ北海道'), (2, '仙台８９ERS'), (3, '秋田ノーザンハピネッツ'), (4, '茨城ロボッツ'), (5, '宇都宮ブレックス'), (6, '群馬クレインサンダーズ'), (7, '越谷アルファーズ'), (8, 'アルティーリ千葉'), (9, '千葉ジェッツ'), (10, 'アルバルク東京'), (11, 'サンロッカーズ渋谷'), (12, '川崎ブレイブサンダース'), (13, '横浜ビー・コルセアーズ'), (14, '富山グラウジーズ'), (15, '三遠ネオフェニックス'), (16, 'シーホース三河'), (17, 'ファイティングイーグルス名古屋'), (18, '名古屋ダイヤモンドドルフィンズ'), (19, '滋賀レイクス'), (20, '京都ハンナリーズ'), (21, '大阪エヴェッサ'), (22, '島根スサノオマジック'), (23, '広島ドラゴンフライズ'), (24, '佐賀バルーナーズ'), (25, '長崎ヴェルカ'), (26, '琉球ゴールデンキングス')], default=1, verbose_name='ホームチーム名')),
                ('away_team_name', models.IntegerField(choices=[(1, 'レバンガ北海道'), (2, '仙台８９ERS'), (3, '秋田ノーザンハピネッツ'), (4, '茨城ロボッツ'), (5, '宇都宮ブレックス'), (6, '群馬クレインサンダーズ'), (7, '越谷アルファーズ'), (8, 'アルティーリ千葉'), (9, '千葉ジェッツ'), (10, 'アルバルク東京'), (11, 'サンロッカーズ渋谷'), (12, '川崎ブレイブサンダース'), (13, '横浜ビー・コルセアーズ'), (14, '富山グラウジーズ'), (15, '三遠ネオフェニックス'), (16, 'シーホース三河'), (17, 'ファイティングイーグルス名古屋'), (18, '名古屋ダイヤモンドドルフィンズ'), (19, '滋賀レイクス'), (20, '京都ハンナリーズ'), (21, '大阪エヴェッサ'), (22, '島根スサノオマジック'), (23, '広島ドラゴンフライズ'), (24, '佐賀バルーナーズ'), (25, '長崎ヴェルカ'), (26, '琉球ゴールデンキングス')], default=2, verbose_name='アウェイチーム名')),
                ('status', models.IntegerField(choices=[(1, '公開'), (2, '非公開')], default=1, verbose_name='公開範囲')),
                ('watch_date', models.DateField(verbose_name='観戦日')),
                ('memory', models.TextField(verbose_name='感想')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='公開日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
    ]
